name: Publish metaflow-checkpoint to pypi and anaconda (Manual)
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.11'
    - name: Install Python 3.x dependencies
      run: |
        python3 -m pip install --upgrade pip==22.3.1
        pip3 install setuptools==65.5.0 wheel==0.38.4 twine==4.0.2
    - name: Build package
      run: |
        python3 setup.py sdist bdist_wheel --universal
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
      with:
        miniforge-version: latest
    - name: Build conda package
      shell: bash -el {0}
      run: |
        conda install -y conda-build anaconda-client
        conda build --output-folder conda-dist conda/
    - name: Publish pypi package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: ./dist
    - name: Publish conda package
      shell: bash -el {0}
      run: |
        anaconda --token ${{ secrets.ANACONDA_REPO_TOKEN }} upload --user outerbounds --label main --skip-existing conda-dist/noarch/metaflow-checkpoint-*